apply plugin: 'com.android.application'

android {
    namespace = 'br.com.pilovieira.gt06'
    compileSdk = 37
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    defaultConfig {
        applicationId = "br.com.pilovieira.gt06"
        minSdk = 23
        targetSdk = 37
        versionCode = 4
        versionName = "3.0.1"
        vectorDrawables.useSupportLibrary = true
    }

    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            applicationIdSuffix ".developer"
        }
    }

    buildFeatures {
        viewBinding = true
    }
}

dependencies {
    implementation 'com.google.android.material:material:1.14.0'
    implementation 'androidx.appcompat:appcompat:1.8.0'

    implementation 'com.google.android.gms:play-services-ads:25.4.0'
    implementation 'com.google.android.gms:play-services-maps:20.0.0'

    implementation 'com.j256.ormlite:ormlite-android:6.1'
}
